# Generated by Django 4.0.3 on 2022-04-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serie',
            table='serie',
        ),
    ]
