# Generated by Django 4.0.3 on 2022-04-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_serie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serie',
            table=None,
        ),
    ]
